version: "2"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ulimits:
      memlock: -1
    mem_limit: 1g
    memswap_limit: 1g
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      elasticsearch_yml: |
        network.host: 0.0.0.0
        bootstrap.mlockall: true
    ports:
      - "9200:9200"
      - "9300:9300"

  app: 
    image: node:6.9.1
    container_name: app
    command: tail -f /dev/null
    working_dir: /home/root
    links:
      - mongo
      - elasticsearch
      - redis
    volumes:
      - ./:/home/root
    ports:
      - "8080:8080"
