version: "2"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  elasticsearch:
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
